### PR TITLE
feat: alternate AM key

### PR DESCRIPTION
**Pull request by michaelBelsanti**
Adds a config options "am_key" that lets you change the modifier key used for activation mode. This patch lets you use control or alt.

#10

### CODE REVIEW

**Comment by abenz1267** [comment]
Thanks for the PR. A few things:

- now that there's 2 config options for AM: please make it a separate struct to bundle it's options
- make the alt config a boolean `use_alt`, that way there's no accidential "why does the key i set not work" as it'd just silently default to ctrl.

**Comment by michaelBelsanti** [comment]
> * make the alt config a boolean `use_alt`, that way there's no accidential "why does the key i set not work" as it'd just silently default to ctrl.

Sounds good, wasn't sure if it'd be worth adding other modifiers, but alt is the only other one i think makes sense anyways

**Comment by abenz1267** [comment]
i'll merge so you get the contribution and will quickly refactor myself, because i want to push an update shortly and would like this to be in.

thanks!

**Comment by michaelBelsanti** [comment]
no problem, thank you!

**Pull request merged**
